/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Consulta;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import modelo.AlimentoPerro;

/**
 *
 * @author Stephanie
 */
public class ActualizarAP extends javax.swing.JFrame {
    
    Consulta registro = new Consulta();

    /**
     * Creates new form ActualizarAP
     */
    public ActualizarAP() {
        initComponents();
        this.jtxt_nombrep.setEditable(false);
        this.jtxt_marca.setEditable(false);
        this.jtxt_fechap.setEditable(false);
        this.jtxt_preciop.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxt_idBuscarP = new javax.swing.JTextField();
        jbtn_buscarP = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtxt_nombrep = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxt_marca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxt_fechap = new javax.swing.JTextField();
        jbtn_modificarp = new javax.swing.JButton();
        jbtn_actualizarp = new javax.swing.JButton();
        jtxt_volverp = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jtxt_preciop = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Actualizar Comida Perro");

        jLabel1.setText("ID:");

        jbtn_buscarP.setText("Buscar");
        jbtn_buscarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_buscarPActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre:");

        jtxt_nombrep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_nombrepActionPerformed(evt);
            }
        });

        jLabel3.setText("Marca:");

        jLabel4.setText("Fecha Ingreso:");

        jtxt_fechap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_fechapActionPerformed(evt);
            }
        });

        jbtn_modificarp.setText("Modificar");
        jbtn_modificarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_modificarpActionPerformed(evt);
            }
        });

        jbtn_actualizarp.setText("Actualizar");
        jbtn_actualizarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_actualizarpActionPerformed(evt);
            }
        });

        jtxt_volverp.setText("Volver");
        jtxt_volverp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_volverpActionPerformed(evt);
            }
        });

        jLabel5.setText("Precio:");

        jtxt_preciop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_preciopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jbtn_modificarp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxt_idBuscarP, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addComponent(jbtn_buscarP))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtxt_marca, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                    .addComponent(jtxt_nombrep)
                                    .addComponent(jtxt_fechap)
                                    .addComponent(jtxt_preciop, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtn_actualizarp)
                        .addGap(57, 57, 57)
                        .addComponent(jtxt_volverp)))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxt_idBuscarP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_buscarP))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxt_nombrep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxt_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxt_fechap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_preciop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_modificarp)
                    .addComponent(jbtn_actualizarp)
                    .addComponent(jtxt_volverp))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_buscarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_buscarPActionPerformed
       int id = Integer.parseInt(this.jtxt_idBuscarP.getText());
       
       AlimentoPerro alimentoPerro = registro.buscarAlimentoPerro(id);
       
       String nombre = alimentoPerro.getNombre();
       String marca = alimentoPerro.getMarca();
       int precio = alimentoPerro.getPrecio();
       Date fecha = alimentoPerro.getFechaIngreso();
       
       this.jtxt_nombrep.setText(nombre);
       this.jtxt_marca.setText(marca);
       this.jtxt_preciop.setText(String.valueOf(precio));
       this.jtxt_fechap.setText(""+fecha);
    }//GEN-LAST:event_jbtn_buscarPActionPerformed

    private void jtxt_nombrepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_nombrepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_nombrepActionPerformed

    private void jtxt_fechapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_fechapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_fechapActionPerformed

    private void jtxt_preciopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_preciopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_preciopActionPerformed

    private void jbtn_modificarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_modificarpActionPerformed
        this.jtxt_nombrep.setEditable(true);
        this.jtxt_marca.setEditable(true);
        this.jtxt_fechap.setEditable(true);
        this.jtxt_preciop.setEditable(true);
        this.jtxt_nombrep.requestFocus();
    }//GEN-LAST:event_jbtn_modificarpActionPerformed

    private void jtxt_volverpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_volverpActionPerformed
        dispose();
    }//GEN-LAST:event_jtxt_volverpActionPerformed

    private void jbtn_actualizarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_actualizarpActionPerformed
        int precio, id;
        String nombre,marca;
        
        id = Integer.parseInt(this.jtxt_idBuscarP.getText());
        precio = Integer.parseInt(this.jtxt_preciop.getText());
        nombre = this.jtxt_nombrep.getText();
        marca = this.jtxt_marca.getText();
        
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyy");
        Date fecha = null;
        
        try {
            fecha= formato.parse(this.jtxt_fechap.getText());
        } catch (ParseException e) {
            
            System.out.println("Error al actualizar fecha" + e.getMessage());
        }
        AlimentoPerro alimentoPerro = new AlimentoPerro(id, nombre, marca, fecha, precio, true);
        
        registro.actualizar(alimentoPerro);
        JOptionPane.showMessageDialog(null, "Datos Actualizados Correctamente", "Aviso", 2);
    }//GEN-LAST:event_jbtn_actualizarpActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ActualizarAP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ActualizarAP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ActualizarAP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ActualizarAP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ActualizarAP().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbtn_actualizarp;
    private javax.swing.JButton jbtn_buscarP;
    private javax.swing.JButton jbtn_modificarp;
    private javax.swing.JTextField jtxt_fechap;
    private javax.swing.JTextField jtxt_idBuscarP;
    private javax.swing.JTextField jtxt_marca;
    private javax.swing.JTextField jtxt_nombrep;
    private javax.swing.JTextField jtxt_preciop;
    private javax.swing.JButton jtxt_volverp;
    // End of variables declaration//GEN-END:variables
}
