/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Consulta;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import modelo.AlimentoGato;
import modelo.AlimentoPerro;

/**
 *
 * @author Stephanie
 */
public class AgregarAG extends javax.swing.JFrame {

    /**
     * Creates new form AgregarAG
     */
    public AgregarAG() {
        initComponents();
        this.jbtn_regresarAG.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxt_MarcaAG = new javax.swing.JTextField();
        jtxt_nombreAG = new javax.swing.JTextField();
        jtxt_diaAG = new javax.swing.JTextField();
        jtxt_mesAG = new javax.swing.JTextField();
        jtxt_añoAG = new javax.swing.JTextField();
        jtxt_precioAG = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jchk_estadoAG = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jbtn_guardarAG = new javax.swing.JButton();
        jbtn_regresarAG = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Alimento de Gato");

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setText("Nombre:");

        jLabel2.setText("Marca:");

        jLabel3.setText("Fecha de Ingreso:");

        jLabel4.setText("Precio:");

        jtxt_MarcaAG.setText("Ingrese Marca");
        jtxt_MarcaAG.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxt_MarcaAGFocusGained(evt);
            }
        });

        jtxt_nombreAG.setText("Ingrese Nombre");
        jtxt_nombreAG.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxt_nombreAGFocusGained(evt);
            }
        });
        jtxt_nombreAG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_nombreAGActionPerformed(evt);
            }
        });

        jtxt_diaAG.setText("Día");
        jtxt_diaAG.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxt_diaAGFocusGained(evt);
            }
        });
        jtxt_diaAG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_diaAGActionPerformed(evt);
            }
        });

        jtxt_mesAG.setText("Mes");
        jtxt_mesAG.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxt_mesAGFocusGained(evt);
            }
        });

        jtxt_añoAG.setText("Año");
        jtxt_añoAG.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxt_añoAGFocusGained(evt);
            }
        });

        jtxt_precioAG.setText("Ingrese Precio");
        jtxt_precioAG.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxt_precioAGFocusGained(evt);
            }
        });

        jLabel5.setText("Estado Disponible ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(68, 68, 68))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(79, 79, 79)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxt_MarcaAG)
                            .addComponent(jtxt_nombreAG))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jtxt_diaAG, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxt_mesAG, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jtxt_añoAG, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jtxt_precioAG, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)))
                        .addComponent(jchk_estadoAG)
                        .addGap(72, 72, 72))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxt_nombreAG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxt_MarcaAG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxt_diaAG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt_mesAG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt_añoAG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jchk_estadoAG, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jtxt_precioAG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jbtn_guardarAG.setText("Guardar");
        jbtn_guardarAG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_guardarAGActionPerformed(evt);
            }
        });

        jbtn_regresarAG.setText("Regresar");
        jbtn_regresarAG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_regresarAGActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jbtn_guardarAG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtn_regresarAG)
                .addGap(89, 89, 89))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_guardarAG)
                    .addComponent(jbtn_regresarAG))
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_regresarAGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_regresarAGActionPerformed
        dispose();
    }//GEN-LAST:event_jbtn_regresarAGActionPerformed

    private void jtxt_nombreAGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_nombreAGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_nombreAGActionPerformed

    private void jtxt_nombreAGFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_nombreAGFocusGained
        this.jtxt_nombreAG.setText("");
    }//GEN-LAST:event_jtxt_nombreAGFocusGained

    private void jtxt_MarcaAGFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_MarcaAGFocusGained
        this.jtxt_MarcaAG.setText("");
    }//GEN-LAST:event_jtxt_MarcaAGFocusGained

    private void jtxt_diaAGFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_diaAGFocusGained
        this.jtxt_diaAG.setText("");
    }//GEN-LAST:event_jtxt_diaAGFocusGained

    private void jtxt_diaAGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_diaAGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_diaAGActionPerformed

    private void jtxt_mesAGFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_mesAGFocusGained
        this.jtxt_mesAG.setText("");
    }//GEN-LAST:event_jtxt_mesAGFocusGained

    private void jtxt_añoAGFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_añoAGFocusGained
        this.jtxt_añoAG.setText("");
    }//GEN-LAST:event_jtxt_añoAGFocusGained

    private void jtxt_precioAGFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_precioAGFocusGained
        this.jtxt_precioAG.setText("");
    }//GEN-LAST:event_jtxt_precioAGFocusGained

    private void jbtn_guardarAGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_guardarAGActionPerformed
        String nombre,marca,dia,mes,año,fechaStr;
        Date fecha;
        int precio;
        boolean estado;
        
        nombre = this.jtxt_nombreAG.getText();
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese Nombre", "Validación", 1);
            this.jtxt_nombreAG.requestFocus();
            return;
        }
        
        marca = this.jtxt_MarcaAG.getText();
        if (marca.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese Marca", "Validación", 1);
            this.jtxt_MarcaAG.requestFocus();
            return;
        }
        
        dia = this.jtxt_diaAG.getText();
        mes = this.jtxt_mesAG.getText();
        año = this.jtxt_añoAG.getText();
        
        if (dia.isEmpty() || año.isEmpty() || mes.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe Ingresa Fecha", "Validación", 1);
            this.jtxt_diaAG.requestFocus();
            return;
        }
        
        fechaStr = dia + "/" + mes + "/" + año;
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyy");
        
        try {
            fecha = formato.parse(fechaStr);
            
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Debe Ingresar fecha en Formato Correcto (dd/MM/yyyy)", "Validación", 1);
            this.jtxt_diaAG.requestFocus();
            return;
        }
        
        try {
            precio = Integer.parseInt(this.jtxt_precioAG.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ERROR: El precio debe ser numérico", "Validación", 1);
            this.jtxt_precioAG.requestFocus();
            return;            
        }
        
        estado = this.jchk_estadoAG.isSelected();
        
        AlimentoGato alimentoGato =  new AlimentoGato(0, nombre, marca, fecha, precio, estado);
        Consulta registro = new Consulta();
        
        if (registro.agregarG(alimentoGato)) {
            JOptionPane.showMessageDialog(this, "Producto Agregado", "Aviso", 1);
            
        }
        else{
            JOptionPane.showMessageDialog(this, "No fue posible agregar el producto", "Aviso", 1);
        }                  
                
         
    }//GEN-LAST:event_jbtn_guardarAGActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AgregarAG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AgregarAG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AgregarAG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AgregarAG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AgregarAG().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtn_guardarAG;
    private javax.swing.JButton jbtn_regresarAG;
    private javax.swing.JCheckBox jchk_estadoAG;
    private javax.swing.JTextField jtxt_MarcaAG;
    private javax.swing.JTextField jtxt_añoAG;
    private javax.swing.JTextField jtxt_diaAG;
    private javax.swing.JTextField jtxt_mesAG;
    private javax.swing.JTextField jtxt_nombreAG;
    private javax.swing.JTextField jtxt_precioAG;
    // End of variables declaration//GEN-END:variables
}
