/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Consulta;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import modelo.AlimentoPerro;

/**
 *
 * @author Stephanie
 */
public class AgregarAP extends javax.swing.JFrame {

    /**
     * Creates new form AgregarAP
     */
    public AgregarAP() {
        initComponents();
        this.jbtn_regresarap.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxt_nombreap = new javax.swing.JTextField();
        jtxt_marcaap = new javax.swing.JTextField();
        jtxt_diaap = new javax.swing.JTextField();
        jtxt_mesap = new javax.swing.JTextField();
        jtxt_añoap = new javax.swing.JTextField();
        jtxt_precioap = new javax.swing.JTextField();
        jchk_estadoap = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jbtn_guardarap = new javax.swing.JButton();
        jbtn_regresarap = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Alimento de Perro");

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setText("Nombre");

        jLabel2.setText("Marca");

        jLabel3.setText("Fecha de Ingreso");

        jLabel4.setText("Precio");

        jLabel5.setText("Estado Disponible");

        jtxt_nombreap.setText("Ingrese Nombre ");
        jtxt_nombreap.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxt_nombreapFocusGained(evt);
            }
        });

        jtxt_marcaap.setText("Ingrese Marca");
        jtxt_marcaap.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxt_marcaapFocusGained(evt);
            }
        });

        jtxt_diaap.setText("Día");
        jtxt_diaap.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxt_diaapFocusGained(evt);
            }
        });

        jtxt_mesap.setText("Mes");
        jtxt_mesap.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxt_mesapFocusGained(evt);
            }
        });
        jtxt_mesap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_mesapActionPerformed(evt);
            }
        });

        jtxt_añoap.setText("Año");
        jtxt_añoap.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxt_añoapFocusGained(evt);
            }
        });
        jtxt_añoap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_añoapActionPerformed(evt);
            }
        });

        jtxt_precioap.setText("Ingrese Precio");
        jtxt_precioap.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxt_precioapFocusGained(evt);
            }
        });
        jtxt_precioap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_precioapActionPerformed(evt);
            }
        });

        jchk_estadoap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchk_estadoapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtxt_precioap, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jchk_estadoap))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jtxt_marcaap, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtxt_nombreap)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jtxt_diaap, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtxt_mesap, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtxt_añoap, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxt_nombreap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxt_marcaap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtxt_diaap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtxt_mesap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtxt_añoap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jtxt_precioap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(jchk_estadoap, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(28, 28, 28))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jbtn_guardarap.setText("Guardar");
        jbtn_guardarap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_guardarapActionPerformed(evt);
            }
        });

        jbtn_regresarap.setText("Regresar");
        jbtn_regresarap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_regresarapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jbtn_guardarap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtn_regresarap)
                .addGap(103, 103, 103))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_guardarap)
                    .addComponent(jbtn_regresarap))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jchk_estadoapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchk_estadoapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jchk_estadoapActionPerformed

    private void jtxt_añoapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_añoapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_añoapActionPerformed

    private void jbtn_regresarapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_regresarapActionPerformed
        dispose();
    }//GEN-LAST:event_jbtn_regresarapActionPerformed

    private void jtxt_precioapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_precioapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_precioapActionPerformed

    private void jtxt_mesapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_mesapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_mesapActionPerformed

    private void jtxt_nombreapFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_nombreapFocusGained
        this.jtxt_nombreap.setText("");
    }//GEN-LAST:event_jtxt_nombreapFocusGained

    private void jtxt_marcaapFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_marcaapFocusGained
        this.jtxt_marcaap.setText("");
    }//GEN-LAST:event_jtxt_marcaapFocusGained

    private void jtxt_diaapFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_diaapFocusGained
        this.jtxt_diaap.setText("");
    }//GEN-LAST:event_jtxt_diaapFocusGained

    private void jtxt_mesapFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_mesapFocusGained
        this.jtxt_mesap.setText("");
    }//GEN-LAST:event_jtxt_mesapFocusGained

    private void jtxt_añoapFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_añoapFocusGained
        this.jtxt_añoap.setText("");
    }//GEN-LAST:event_jtxt_añoapFocusGained

    private void jtxt_precioapFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_precioapFocusGained
        this.jtxt_precioap.setText("");
    }//GEN-LAST:event_jtxt_precioapFocusGained

    private void jbtn_guardarapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_guardarapActionPerformed
        String nombre,marca,dia,mes,año,fechaStr;
        Date fecha;
        int precio;
        boolean estado;
        
        nombre = this.jtxt_nombreap.getText();
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese Nombre", "Validación", 1);
            this.jtxt_nombreap.requestFocus();
            return;
        }
        
        marca = this.jtxt_marcaap.getText();
        if (marca.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese Marca", "Validación", 1);
            this.jtxt_marcaap.requestFocus();
            return;
        }
        
        dia = this.jtxt_diaap.getText();
        mes = this.jtxt_mesap.getText();
        año = this.jtxt_añoap.getText();
        
        if (dia.isEmpty() || año.isEmpty() || mes.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe Ingresa Fecha", "Validación", 1);
            this.jtxt_diaap.requestFocus();
            return;
        }
        
        fechaStr = dia + "/" + mes + "/" + año;
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyy");
        
        try {
            fecha = formato.parse(fechaStr);
            
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Debe Ingresar fecha en Formato Correcto (dd/MM/yyyy)", "Validación", 1);
            this.jtxt_diaap.requestFocus();
            return;
        }
        
        try {
            precio = Integer.parseInt(this.jtxt_precioap.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ERROR: El precio debe ser numérico", "Validación", 1);
            this.jtxt_precioap.requestFocus();
            return;            
        }
        
        estado = this.jchk_estadoap.isSelected();
        
        AlimentoPerro alimentoPerro =  new AlimentoPerro(0, nombre, marca, fecha, precio, estado);
        Consulta registro = new Consulta();
        
        if (registro.agregar(alimentoPerro)) {
            JOptionPane.showMessageDialog(this, "Producto Agregado", "Aviso", 1);
            
        }
        else{
            JOptionPane.showMessageDialog(this, "No fue posible agregar el producto", "Aviso", 1);
        }
                
    }//GEN-LAST:event_jbtn_guardarapActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AgregarAP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AgregarAP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AgregarAP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AgregarAP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AgregarAP().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtn_guardarap;
    private javax.swing.JButton jbtn_regresarap;
    private javax.swing.JCheckBox jchk_estadoap;
    private javax.swing.JTextField jtxt_añoap;
    private javax.swing.JTextField jtxt_diaap;
    private javax.swing.JTextField jtxt_marcaap;
    private javax.swing.JTextField jtxt_mesap;
    private javax.swing.JTextField jtxt_nombreap;
    private javax.swing.JTextField jtxt_precioap;
    // End of variables declaration//GEN-END:variables
}
