/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista;

import controlador.Consulta;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import modelo.Accesorio;
import modelo.AlimentoPerro;

/**
 *
 * @author Evelyn
 */
public class AgregarA extends javax.swing.JFrame {

    /** Creates new form AgregarA */
    public AgregarA() {
        initComponents();
        this.jbtn_regresarA.requestFocus();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxt_nombreA = new javax.swing.JTextField();
        jtxt_marcaA = new javax.swing.JTextField();
        jtxt_diaA = new javax.swing.JTextField();
        jtxt_precioA = new javax.swing.JTextField();
        jtxt_mesA = new javax.swing.JTextField();
        jtxt_añoA = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jchk_estadoA = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jbtn_guardarA = new javax.swing.JButton();
        jbtn_regresarA = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Accesorio");

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setText("Nombre:");

        jLabel2.setText("Marca:");

        jLabel3.setText("Fecha de Ingreso:");

        jLabel4.setText("Precio:");

        jtxt_nombreA.setText("Ingrese Nombre");
        jtxt_nombreA.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxt_nombreAFocusGained(evt);
            }
        });

        jtxt_marcaA.setText("Ingrese Marca");
        jtxt_marcaA.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxt_marcaAFocusGained(evt);
            }
        });

        jtxt_diaA.setText("Día");
        jtxt_diaA.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxt_diaAFocusGained(evt);
            }
        });

        jtxt_precioA.setText("Ingrese Precio");
        jtxt_precioA.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxt_precioAFocusGained(evt);
            }
        });
        jtxt_precioA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_precioAActionPerformed(evt);
            }
        });

        jtxt_mesA.setText("Mes");
        jtxt_mesA.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxt_mesAFocusGained(evt);
            }
        });

        jtxt_añoA.setText("Año");
        jtxt_añoA.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxt_añoAFocusGained(evt);
            }
        });

        jLabel5.setText("Estado Disponible");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(40, 40, 40))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(51, 51, 51)))
                                .addGap(17, 17, 17)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtxt_marcaA, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxt_nombreA, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxt_diaA, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jtxt_mesA, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxt_añoA, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(jtxt_precioA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jchk_estadoA)
                        .addGap(57, 57, 57))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxt_nombreA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxt_marcaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxt_diaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt_mesA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt_añoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jchk_estadoA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jtxt_precioA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jbtn_guardarA.setText("Guardar");
        jbtn_guardarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_guardarAActionPerformed(evt);
            }
        });

        jbtn_regresarA.setText("Regresar");
        jbtn_regresarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_regresarAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jbtn_guardarA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtn_regresarA)
                .addGap(83, 83, 83))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_guardarA)
                    .addComponent(jbtn_regresarA))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxt_precioAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_precioAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_precioAActionPerformed

    private void jbtn_regresarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_regresarAActionPerformed
        dispose();
    }//GEN-LAST:event_jbtn_regresarAActionPerformed

    private void jtxt_nombreAFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_nombreAFocusGained
        this.jtxt_nombreA.setText("");
    }//GEN-LAST:event_jtxt_nombreAFocusGained

    private void jtxt_marcaAFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_marcaAFocusGained
        this.jtxt_marcaA.setText("");
    }//GEN-LAST:event_jtxt_marcaAFocusGained

    private void jtxt_diaAFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_diaAFocusGained
        this.jtxt_diaA.setText("");
    }//GEN-LAST:event_jtxt_diaAFocusGained

    private void jtxt_mesAFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_mesAFocusGained
       this.jtxt_mesA.setText("");
    }//GEN-LAST:event_jtxt_mesAFocusGained

    private void jtxt_añoAFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_añoAFocusGained
        this.jtxt_añoA.setText("");
    }//GEN-LAST:event_jtxt_añoAFocusGained

    private void jtxt_precioAFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_precioAFocusGained
        this.jtxt_precioA.setText("");
    }//GEN-LAST:event_jtxt_precioAFocusGained

    private void jbtn_guardarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_guardarAActionPerformed
        String nombre,marca,dia,mes,año,fechaStr;
        Date fecha;
        int precio;
        boolean estado;
        
        nombre = this.jtxt_nombreA.getText();
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese Nombre", "Validación", 1);
            this.jtxt_nombreA.requestFocus();
            return;
        }
        
        marca = this.jtxt_marcaA.getText();
        if (marca.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese Marca", "Validación", 1);
            this.jtxt_marcaA.requestFocus();
            return;
        }
        
        dia = this.jtxt_diaA.getText();
        mes = this.jtxt_mesA.getText();
        año = this.jtxt_añoA.getText();
        
        if (dia.isEmpty() || año.isEmpty() || mes.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe Ingresa Fecha", "Validación", 1);
            this.jtxt_diaA.requestFocus();
            return;
        }
        
        fechaStr = dia + "/" + mes + "/" + año;
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyy");
        
        try {
            fecha = formato.parse(fechaStr);
            
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Debe Ingresar fecha en Formato Correcto (dd/MM/yyyy)", "Validación", 1);
            this.jtxt_diaA.requestFocus();
            return;
        }
        
        try {
            precio = Integer.parseInt(this.jtxt_precioA.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ERROR: El precio debe ser numérico", "Validación", 1);
            this.jtxt_precioA.requestFocus();
            return;            
        }
        
        estado = this.jchk_estadoA.isSelected();
        
        Accesorio accesorio =  new Accesorio(0, nombre, marca, fecha, precio, estado);
        Consulta registro = new Consulta();
        
        if (registro.agregarA(accesorio)) {
            JOptionPane.showMessageDialog(this, "Producto Agregado", "Aviso", 1);
            
        }
        else{
            JOptionPane.showMessageDialog(this, "No fue posible agregar el producto", "Aviso", 1);
        }                
        
    }//GEN-LAST:event_jbtn_guardarAActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AgregarA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AgregarA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AgregarA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AgregarA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AgregarA().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtn_guardarA;
    private javax.swing.JButton jbtn_regresarA;
    private javax.swing.JCheckBox jchk_estadoA;
    private javax.swing.JTextField jtxt_añoA;
    private javax.swing.JTextField jtxt_diaA;
    private javax.swing.JTextField jtxt_marcaA;
    private javax.swing.JTextField jtxt_mesA;
    private javax.swing.JTextField jtxt_nombreA;
    private javax.swing.JTextField jtxt_precioA;
    // End of variables declaration//GEN-END:variables

}
