/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Consulta;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import modelo.AlimentoPerro;

/**
 *
 * @author Evelyn
 */
public class ListarAP extends javax.swing.JFrame {

    /**
     * Creates new form ListarAP
     */
    public ListarAP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxt_idBuscarap = new javax.swing.JTextField();
        jbtn_buscarap = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_datosap = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listar Alimento Perro");

        jLabel1.setText("Ingrese ID Producto:");

        jtxt_idBuscarap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_idBuscarapActionPerformed(evt);
            }
        });

        jbtn_buscarap.setText("Buscar Producto");
        jbtn_buscarap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_buscarapActionPerformed(evt);
            }
        });

        jtbl_datosap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Marca", "Precio", "Disponibilidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtbl_datosap);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jtxt_idBuscarap, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jbtn_buscarap)
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxt_idBuscarap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_buscarap))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_buscarapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_buscarapActionPerformed
        String nombre,marca;
        int id, precio;
        boolean estado;
        
        Consulta registro = new Consulta();
        DefaultTableModel modelo = (DefaultTableModel) this.jtbl_datosap.getModel();
        
        try {
            id = Integer.parseInt(this.jtxt_idBuscarap.getText());
        } catch (NumberFormatException e) {
            id = 0;            
        }
        
        modelo.setRowCount(0);
        
        if (id == 0) {
            List<AlimentoPerro> listaap = registro.listarAP();
            for (AlimentoPerro alimentoPerro : listaap) {
                id = alimentoPerro.getIdAlimentoPerro();
                nombre = alimentoPerro.getNombre();
                marca = alimentoPerro.getMarca();
                precio = alimentoPerro.getPrecio();
                estado = alimentoPerro.isEstado();
            
                modelo.addRow(new Object [] {id,nombre,marca,precio,estado});
            }
                  
        } else {
            AlimentoPerro alimentoPerro = registro.buscarAlimentoPerro(id);
            id = alimentoPerro.getIdAlimentoPerro();
                nombre = alimentoPerro.getNombre();
                marca = alimentoPerro.getMarca();
                precio = alimentoPerro.getPrecio();
                estado = alimentoPerro.isEstado();
                modelo.addRow(new Object [] {id,nombre,marca,precio,estado});
        }
    }//GEN-LAST:event_jbtn_buscarapActionPerformed

    private void jtxt_idBuscarapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_idBuscarapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_idBuscarapActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ListarAP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ListarAP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ListarAP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ListarAP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarAP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtn_buscarap;
    private javax.swing.JTable jtbl_datosap;
    private javax.swing.JTextField jtxt_idBuscarap;
    // End of variables declaration//GEN-END:variables
}
